### ISSUE TITLE
build_runner build_runner serve --live-reload doesn't reload on changes

### ISSUE THREAD

**Issue by jhenso** [dart-lang/build#3379]
Hello, according to [build_runner documentation](https://pub.dev/packages/build_runner):

> Some commands also have additional options:

> serve
> --hostname: The host to run the server on.
> --live-reload: Enables automatic page reloading on rebuilds.

However if you run `dart run build_runner serve --live-reload`, the application is built and served, but live-reload doesn't work, with the following error when the browser tries to connect to the WebSocket:

```
Serving `web` on http://localhost:8080
ERROR - 2022-10-17 10:06:11.398101
Asynchronous error
NoSuchMethodError: Closure call with mismatched arguments: function 'BuildUpdatesWebSocketHandler.createHandlerByRootDir.closureForRootDir'
Receiver: Closure: (WebSocketChannel, String) => void
Tried calling: BuildUpdatesWebSocketHandler.createHandlerByRootDir.closureForRootDir(Instance of 'WebSocketChannel')
Found: BuildUpdatesWebSocketHandler.createHandlerByRootDir.closureForRootDir(WebSocketChannel, String) => void
dart:core                                                   _objectNoSuchMethod
package:shelf_web_socket/shelf_web_socket.dart 49:55        webSocketHandler.<fn>
package:shelf_web_socket/src/web_socket_handler.dart 81:20  WebSocketHandler.handle.<fn>
``` 

Repository with minimal reproduction: https://github.com/jhenso/dart-build-runner

* Dart SDK Version (`dart --version`)
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_x64"

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

-   build_runner 2.3.0
-   build_runner_core 7.2.4
-   build_web_compilers 3.2.6

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOSX
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

**Comment by grouma** [comment]
I'm not sure what `client ID` you are referring to. I'm pretty sure this has been broken since https://github.com/dart-lang/build/pull/1786. I'm not sure why `closureForRootDir` takes a `String protocol` parameter.

**Comment by jakemac53** [comment]
I am probably just misremembering, I hadn't actually looked into this at all I just thought you had added something for multiple apps on the page so we could know which one we were talking to

**Comment by jakemac53** [comment]
@jhenso if you want to take a look at fixing this we would accept a PR. Given it has been broken for a long time without any issues being filed, it probably isn't going to be high priority to fix.

**Comment by simolus3** [comment]
It looks like this is actually a bug in `shelf_web_socket`, this should be `(Never, Never)` to test for a binary function. `Null` is no longer a bottom type, so `build_runner`'s callback of `void Function(WebSocketChannel, String)` is not a `void Function(Null, Null)`.

https://github.com/dart-lang/shelf/blob/39d820d4e32fc99c65f562786097487d597dcee1/pkgs/shelf_web_socket/lib/shelf_web_socket.dart#L46

Why this surfaces in `build_runner` and not in `shelf_web_socket` tests is another question. Do these original tests not run with sound null safety?
